import RandomNumber from "./RandomNumber";

export default function RandomQuote() {
    const quotes = [
        "No pain, no gain.",
        "Push yourself because no one else is going to do it for you.",
        "Sweat is just fat crying.",
        "The only bad workout is the one you didn’t do.",
        "Strive for progress, not perfection.",
        "Don’t limit your challenges, challenge your limits.",
        "Excuses don’t burn calories.",
        "Pain is temporary. Pride is forever.",
        "Your body can stand almost anything. It’s your mind you have to convince.",
        "Be stronger than your strongest excuse.",
        "Fitness is like a relationship. You can’t cheat and expect it to work.",
        "You don’t have to be extreme, just consistent.",
        "The body achieves what the mind believes.",
        "Fall in love with taking care of yourself.",
        "Work hard in silence, let your success be your noise.",
        "Don’t stop when you’re tired. Stop when you’re done.",
        "Excuses are for people who don’t want it bad enough.",
        "The only way to finish is to start.",
        "Train insane or remain the same.",
        "Your health is an investment, not an expense.",
        "Champions are made when no one is watching.",
        "Success starts with self-discipline.",
        "The hardest lift of all is lifting your butt off the couch.",
        "You are stronger than you think.",
        "Strength doesn’t come from what you can do. It comes from overcoming the things you once thought you couldn’t.",
        "Don’t wish for it, work for it.",
        "Fitness is not about being better than someone else. It’s about being better than you used to be.",
        "Wake up. Work out. Look hot. Kick ass.",
        "Sore today, strong tomorrow.",
        "Discipline is choosing between what you want now and what you want most.",
        "Great things never came from comfort zones.",
        "Motivation gets you started. Habit keeps you going.",
        "It never gets easier. You just get stronger.",
        "Set goals. Smash them. Repeat.",
        "Don’t count the days, make the days count.",
        "A one-hour workout is only 4% of your day. No excuses.",
        "Strength is built in the moments you want to quit.",
        "Train like a beast, look like a beauty.",
        "Your future self will thank you for the workout you do today.",
        "You are your only competition.",
        "Push past the pain, embrace the gain.",
        "Fitness is earned, not given.",
        "Make sweat your best accessory.",
        "Excuses fade, results last.",
        "If it doesn’t challenge you, it won’t change you.",
        "Act like a lady, lift like a boss.",
        "Consistency is more important than perfection.",
        "Pain is weakness leaving the body.",
        "Do it for the after photo.",
        "Every rep brings you closer to your goal.",
        "Push beyond what you think is possible.",
        "The harder you work, the luckier you get.",
        "Your only limit is you.",
        "Consistency beats motivation every time.",
        "Work for it, don’t wish for it.",
        "Fall in love with the process, not the results.",
        "Strong today, stronger tomorrow.",
        "Don’t quit. Suffer now and live the rest of your life as a champion.",
        "Excuses are the enemy of progress.",
        "Train smart, push hard, recover well.",
        "What hurts today makes you stronger tomorrow.",
        "You don’t get the ass you want by sitting on it.",
        "Stop doubting yourself and start doing.",
        "Sweat is your fat waving goodbye.",
        "Progress, not perfection, wins the race.",
        "Your comfort zone is your enemy.",
        "Every workout is a step forward.",
        "Strive for consistency, not perfection.",
        "Fitness is earned one rep at a time.",
        "The pain of discipline is less than the pain of regret.",
        "When you feel like quitting, remember why you started.",
        "Your mind gives up before your body does.",
        "Strong body, strong mind.",
        "Discipline is the bridge between goals and accomplishment.",
        "Train like your life depends on it.",
        "Don’t stop until you’re proud of yourself.",
        "Fitness is a lifestyle, not a hobby.",
        "Turn sweat into success.",
        "The difference between try and triumph is a little 'umph'.",
        "One workout can change your day, consistent workouts change your life.",
        "No one can do it for you—lift, run, push.",
        "Your effort today defines your results tomorrow.",
        "Be relentless in your pursuit of strength.",
        "Stronger than yesterday, weaker than tomorrow.",
        "A little progress each day adds up to big results.",
        "Pain is fuel for growth.",
        "Your body responds to effort, not excuses.",
        "Discipline today leads to freedom tomorrow.",
        "Train hard, live better.",
        "Your comfort zone is where progress goes to die.",
        "Energy follows effort.",
        "Strength grows when you challenge your limits.",
        "The real workout starts when you want to stop.",
        "Fitness isn’t about luck, it’s about effort.",
        "Sweat, sacrifice, succeed.",
        "You are capable of more than you know.",
        "Consistency compounds into results.",
        "The only way out is through."
    ];
    return quotes[RandomNumber(quotes.length - 1)];
}